#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=/dev/null
source "$ROOT_DIR/core.sh"

run_test() {
    local name="$1"
    shift

    if "$@"; then
        printf 'PASS %s\n' "$name"
    else
        printf 'FAIL %s\n' "$name"
        exit 1
    fi
}

assert_eq() {
    local expected="$1"
    local actual="$2"

    [[ "$expected" == "$actual" ]]
}

assert_file_contains_line() {
    local file="$1"
    local line="$2"

    grep -Fqx "$line" "$file"
}

assert_file_line_equals() {
    local file="$1"
    local line_number="$2"
    local expected="$3"
    local actual

    actual="$(sed -n "${line_number}p" "$file")"
    [[ "$actual" == "$expected" ]]
}

assert_gitignore_header() {
    local gitignore_file="$1"

    assert_file_line_equals "$gitignore_file" 1 "# Do not edit this file directly."
    assert_file_line_equals "$gitignore_file" 2 '# Edit ~/.nadm/tracked and run `jj dot sync`'
    assert_file_line_equals "$gitignore_file" 3 ""
    assert_file_line_equals "$gitignore_file" 4 "*"
    assert_file_contains_line "$gitignore_file" "!/.gitignore"
}

captured_action=""
captured_arg=""
captured_error=""

reset_captures() {
    captured_action=""
    captured_arg=""
    captured_error=""
}

cmd_init() {
    captured_action="init"
}

cmd_clone() {
    captured_action="clone"
    captured_arg="${1:-}"
}

error() {
    captured_error="$1"
    return 1
}

test_init_dispatch() {
    reset_captures
    main init
    assert_eq "init" "$captured_action"
}

test_clone_dispatch_url() {
    reset_captures
    main clone https://example.com/repo.git
    assert_eq "clone" "$captured_action" && assert_eq "https://example.com/repo.git" "$captured_arg"
}

test_clone_dispatch_github_shorthand() {
    reset_captures
    main clone --github owner/repo
    assert_eq "clone" "$captured_action" && assert_eq "https://github.com/owner/repo.git" "$captured_arg"
}

create_fake_jj() {
    local temp_dir="$1"

    mkdir -p "$temp_dir/bin"
    cat > "$temp_dir/bin/jj" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

if [[ "$1" == "git" && "$2" == "init" ]]; then
    mkdir -p "$HOME/.jj/repo"
    exit 0
fi

if [[ "$1" == "add" ]]; then
    exit 0
fi

if [[ "$1" == "file" && "$2" == "untrack" ]]; then
    exit 0
fi

if [[ "$1" == "dot" ]]; then
    exit 99
fi

exit 0
EOF
    chmod +x "$temp_dir/bin/jj"
}

test_setup_writes_dot_alias_and_bootstrap_files() {
    local temp_dir
    temp_dir="$(mktemp -d)"

    local old_home="$HOME"
    local old_path="$PATH"

    HOME="$temp_dir/home"
    mkdir -p "$HOME"
    create_fake_jj "$temp_dir"
    PATH="$temp_dir/bin:$PATH"

    do_setup

    local config_file="$HOME/.nadm/config.toml"
    local dot_script="$HOME/.nadm/dot.sh"
    local tracked_file="$HOME/.nadm/tracked"
    local gitignore_file="$HOME/.gitignore"

    [[ -f "$config_file" ]] || return 1
    [[ -x "$dot_script" ]] || return 1
    [[ -f "$tracked_file" ]] || return 1
    [[ -f "$gitignore_file" ]] || return 1

    assert_file_contains_line "$config_file" "[aliases]"
    assert_file_contains_line "$config_file" 'dot = ["util", "exec", "--", "bash", "-lc", "~/.nadm/dot.sh \"$@\"", ""]'
    if grep -Fq "sparse" "$config_file"; then
        return 1
    fi

    assert_file_contains_line "$tracked_file" ".nadm/"
    assert_gitignore_header "$gitignore_file"
    assert_file_contains_line "$gitignore_file" "!/.nadm/"
    assert_file_contains_line "$gitignore_file" "!/.nadm/**"

    HOME="$old_home"
    PATH="$old_path"
    rm -rf "$temp_dir"
}

test_dot_sync_handles_files_and_directories() {
    local temp_dir
    temp_dir="$(mktemp -d)"

    local old_home="$HOME"
    local old_path="$PATH"

    HOME="$temp_dir/home"
    mkdir -p "$HOME"
    create_fake_jj "$temp_dir"
    PATH="$temp_dir/bin:$PATH"

    do_setup

    mkdir -p "$HOME/.config/nvim"
    : > "$HOME/.bashrc"

    cat > "$HOME/.nadm/tracked" <<'EOF'
.nadm/
.config/nvim/
.bashrc
EOF

    "$HOME/.nadm/dot.sh" sync

    local gitignore_file="$HOME/.gitignore"
    assert_gitignore_header "$gitignore_file"
    assert_file_contains_line "$gitignore_file" "!/.config/"
    assert_file_contains_line "$gitignore_file" "/.config/*"
    assert_file_contains_line "$gitignore_file" "!/.config/nvim/"
    assert_file_contains_line "$gitignore_file" "!/.config/nvim/**"
    assert_file_contains_line "$gitignore_file" "!/.bashrc"

    HOME="$old_home"
    PATH="$old_path"
    rm -rf "$temp_dir"
}

test_dot_sync_handles_directory_without_trailing_slash() {
    local temp_dir
    temp_dir="$(mktemp -d)"

    local old_home="$HOME"
    local old_path="$PATH"

    HOME="$temp_dir/home"
    mkdir -p "$HOME"
    create_fake_jj "$temp_dir"
    PATH="$temp_dir/bin:$PATH"

    do_setup

    mkdir -p "$HOME/.config/ghostty"

    cat > "$HOME/.nadm/tracked" <<'EOF'
.nadm/
.config/ghostty
EOF

    "$HOME/.nadm/dot.sh" sync

    local gitignore_file="$HOME/.gitignore"
    assert_file_contains_line "$gitignore_file" "!/.config/"
    assert_file_contains_line "$gitignore_file" "/.config/*"
    assert_file_contains_line "$gitignore_file" "!/.config/ghostty/"
    assert_file_contains_line "$gitignore_file" "!/.config/ghostty/**"

    if grep -Fqx "!/.config/ghostty" "$gitignore_file"; then
        return 1
    fi

    HOME="$old_home"
    PATH="$old_path"
    rm -rf "$temp_dir"
}

run_test "dispatches init" test_init_dispatch
run_test "dispatches clone URL" test_clone_dispatch_url
run_test "dispatches clone github shorthand" test_clone_dispatch_github_shorthand
run_test "setup writes dot alias and bootstrap files" test_setup_writes_dot_alias_and_bootstrap_files
run_test "dot sync handles files and directories" test_dot_sync_handles_files_and_directories
run_test "dot sync handles directory without trailing slash" test_dot_sync_handles_directory_without_trailing_slash
